### ISSUE TITLE
Add CI Jobs for Scripts folder on amd64 and arm64

### ISSUE THREAD

**Issue by JWhitleyWork** [autowarefoundation/modelzoo#17]
The `scripts` folder contains `bash` scripts and Dockerfiles which can be tested for functionality on pull requests and pushes. To make sure that nothing breaks, this is recommended.

**Comment by LiyouZhou** [comment]
@JWhitleyWork thank you for raising this issue. we have some x84 patches. will push asap. would require your assistance in setting up an aarch64 runner.

**Comment by LiyouZhou** [comment]
@JWhitleyWork  in order to invoke the CI scripts (047f045651127e9a4931ee14d6923abc9f7bb833), would you be able to push a new docker image to docker hub using the latest master? then the whole process will be automated via the CI.

**Comment by JWhitleyWork** [comment]
Sorry for the delay - I was on holiday. New Docker image has been pushed to https://hub.docker.com/r/autoware/model-zoo-tvm-cli/tags?page=1&ordering=last_updated.

**Comment by LiyouZhou** [comment]
@JWhitleyWork do you think we can have a github runner running on an aarch64 AWS instance like GitLab?

**Comment by JWhitleyWork** [comment]
@LiyouZhou The `arm64` runner has been added and is available for work under this Github organization. To utilize it for a job, just set `runs-on:` to `ARM64` or `self-hosted` (either will trigger the job to run on the `arm64` host).

**Comment by LiyouZhou** [comment]
> @LiyouZhou The `arm64` runner has been added and is available for work under this Github organization. To utilize it for a job, just set `runs-on:` to `ARM64` or `self-hosted` (either will trigger the job to run on the `arm64` host).

Thank you for your help. We will go ahead and test it out.

**Comment by JWhitleyWork** [comment]
Here's an example from Autoware.AI of running jobs for both `x86_64` and `arm64`: https://github.com/Autoware-AI/docker/blob/0d808605034faf5470b00e9a1db73307c400111b/.github/workflows/nightly.yaml#L19

**Comment by JWhitleyWork** [comment]
Closed by #38.
