### ISSUE TITLE
Save compiled networks as artifacts

### ISSUE THREAD

**Issue by ambroise-arm** [autowarefoundation/modelzoo#41]
I am following up on the discussion about providing pre-compiled neural networks in Autoware: https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/932

The idea would be to use Modelzoo's CI to compile the networks and save those so that they can be used inside of Autoware. Then it may be redundant to also commit those as LFS files in gitlab (and also not possible if they get too big).

Keeping them as Github artifacts doesn't sound like a good idea because 1) the storage duration is limited 2) the storage size is limited (and separate from Github's LFS allowance) 3) downloading artifacts seems restricted to registered github users.

An S3 bucket looks like a good solution and gihub actions are available for syncing with it (https://github.com/marketplace/actions/s3-sync). @JWhitleyWork , could you make a bucket available?

The size of the compiled networks for the ones currently in Modelzoo is ~67MB. With initial support for x86_64 + aarch64 on CPU + Vulkan, the total size would get to 250-300MB. But that would grow depending on what will be supported next.

**Comment by LiyouZhou** [comment]
@JWhitleyWork Hi Josh, would you be able to create an S3 bucket that is accessible from CI, please?

**Comment by JWhitleyWork** [comment]
A bucket and associated user has been created. I will email you credentials seperately.

**Comment by JWhitleyWork** [comment]
@ambroise-arm @LiyouZhou I just checked the `autoware-modelzoo` bucket and it looks like the artifacts are not being pushed there. The `s3-sync-action` completes successfully but it looks like it's not actually uploading anything. Can you look into why this might be happening?

**Comment by ambroise-arm** [comment]
@JWhitleyWork The AWS region was not correct in CI. Can you check if it uploaded something this time? If not, I will dig deeper.

**Comment by JWhitleyWork** [comment]
@ambroise-arm Still nothing, unfortunately.

**Comment by JWhitleyWork** [comment]
It worked! The objects were uploaded successfully! The permissions aren't quite right (they're not set to public) but we're almost there!

**Comment by ambroise-arm** [comment]
@JWhitleyWork That's great!

I used to think we wanted public permissions on the objects so that they could be downloaded when building autoware packages, but maybe that would be to much network activity on the bucket. I will soon have a MR in autoware where we can discuss this.

Closing issue as the artifacts are correctly saved.
