### ISSUE TITLE
Template config.hpp input and output type

### ISSUE THREAD

**Issue by angry-crab** [autowarefoundation/modelzoo#81]
The current design of the `config.cpp` assumes that inputs and outputs are always of same type which is not true in some cases. One exapmle is as follows:
https://github.com/angry-crab/tvm_example/blob/c66a43f34c2e30175df0399aa61a2da5a76447e4/scatter_tir.py#L17
We can either include type info either into `networks inputs` and `network outputs`, or make `tvm_dtype_code` a vector.

**Comment by ambroise-arm** [comment]
It will probably be more clear for parsing the information on the Autoware side to have it in the input/output.

**Comment by angry-crab** [comment]
> It will probably be more clear for parsing the information on the Autoware side to have it in the input/output.

But the current pipeline gets all the information from the template .hpp file. Are you suggesting we should remove it?

**Comment by angry-crab** [comment]
> And maybe the dtype_bits and _lanes need to follow the _code.
> And the tvm_cli script and the header template need to accommodate for those changes.

That makes sense. The only issue is that it is not backward compatible anymore.

**Comment by angry-crab** [comment]
I just created a PR to refactor `NetworkNode`. It is defined like this.
```
typedef struct
{
  // Node name
  std::string node_name;

  // Network data type configurations
  DLDataTypeCode tvm_dtype_code;
  int32_t tvm_dtype_bits;
  int32_t tvm_dtype_lanes;

  // Shape info
  std::vector<int64_t> node_shape;
} NetworkNode;
```

**Comment by ambroise-arm** [comment]
> The only issue is that it is not backward compatible anymore.

It is much less of a problem that it would have been before. With the versioning from https://github.com/autowarefoundation/modelzoo/issues/63, the current version will continue to be available and work while the transition happens. 

> Would you be able to accommodate these changes to `tvm_cli`?

Not immediately. But if it is not urgent, then yes.
